version: "3.5"
services:
  nexus:
    image: sonatype/nexus3:3.40.0
    hostname: nexus
    container_name: nexus    
    volumes:
      - ~/docker/nexus/my-nexus-data:/nexus-data
    ports:
      - "8081:8081"
      - "5000:5000"
